//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int iD { get; set; }
        public Nullable<int> cCode { get; set; }
        public string cUserName { get; set; }
        public string cPassWord { get; set; }
        public string cName { get; set; }
        public string cPhone { get; set; }
        public string cAddress { get; set; }
        public string cLinkFace { get; set; }
        public string cCardBank { get; set; }
        public Nullable<int> iBank { get; set; }
        public string cNameFace { get; set; }
        public Nullable<int> iCreateBy { get; set; }
        public Nullable<System.DateTime> dCeateDate { get; set; }
        public Nullable<int> iActive { get; set; }
        public Nullable<int> iDelete { get; set; }
    }
}
