//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserGroup
    {
        public int iD { get; set; }
        public Nullable<int> iUser { get; set; }
        public Nullable<int> iGroup { get; set; }
    }
}
